using FastEndpoints;
using FastEndpoints.OpenApi;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Scalar.AspNetCore;
using TacticusPlanner.Api.Features;
using TacticusPlanner.Api.Features.AccountManagement;
using TacticusPlanner.Api.Features.Auth;
using TacticusPlanner.Api.Features.Guilds;
using TacticusPlanner.Api.Features.PlayerData;
using TacticusPlanner.Api.Features.Projects;
using TacticusPlanner.Api.Features.TacticusIntegration;
using TacticusPlanner.Api.Features.V1Import;
using TacticusPlanner.Api.Http;
using TacticusPlanner.GameCatalog;
using TacticusPlanner.Persistence;
using TacticusPlanner.Persistence.Encryption;
using TacticusPlanner.Persistence.Interceptors;
using TacticusPlanner.ServiceDefaults;
using TacticusPlanner.TacticusApi;

var builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();
builder.Services.AddSingleton(TimeProvider.System);
builder.Services.AddSingleton<EntityMetadataInterceptor>();
builder.AddNpgsqlDbContext<PlannerDbContext>("planner-db");
builder.Services.ConfigureDbContext<PlannerDbContext>((sp, options) =>
{
    options.AddInterceptors(sp.GetRequiredService<EntityMetadataInterceptor>());
});

builder.Services.AddProblemDetails();
builder.Services.AddExceptionHandler<GlobalExceptionHandler>();
builder.Services.Configure<ColumnEncryptionOptions>(
    builder.Configuration.GetSection(ColumnEncryptionOptions.SectionName)
);
builder.Services.AddSingleton<IColumnEncryptionService, AesGcmColumnEncryptionService>();
builder.Services.AddSingleton<IColumnHashService, HmacColumnHashService>();
builder.Services.AddScoped<TacticusApiKeyValidator>();
builder.Services.AddScoped<PlayerDataTransformer>();
builder.Services.AddScoped<GuildSyncService>();
builder.Services.AddScoped<V1GoalImportService>();
builder.Services.AddScoped<ProjectsService>();
builder.Services.AddSingleton<IExternalIdentityDeleter, NoOpExternalIdentityDeleter>();
builder.Services.AddGameCatalog();
builder.Services.AddTacticusApi(builder.Configuration["TacticusApi:BaseUrl"]);
builder.Services.AddTacticusV1Client(
    builder.Configuration["V1Api:BaseUrl"],
    builder.Configuration["V1Api:FunctionsKey"]
);

// OpenAPI is generated by FastEndpoints (FastEndpoints.OpenApi), which wires the FastEndpoints metadata
// and transformers into the Microsoft.AspNetCore.OpenApi pipeline. Per-endpoint summaries come from each
// endpoint's Configure()/Summary(), so there is no hand-maintained route-description table here.
builder.Services
    .AddFastEndpoints()
    .OpenApiDocument(options =>
    {
        options.DocumentName = "v1";
        options.Title = "Tacticus Planner API";
        options.Version = "v1";
        options.EnableJWTBearerAuth = true;
    });

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.Authority = builder.Configuration["Authentication:Authority"];
        options.Audience = builder.Configuration["Authentication:Audience"];
        options.MapInboundClaims = false;
        options.TokenValidationParameters = new TokenValidationParameters
        {
            NameClaimType = "name",
            RoleClaimType = "roles",
        };
    });

builder.Services
    .AddAuthorizationBuilder()
    .AddPolicy(
        AuthorizationPolicies.AccessAsUser,
        policy =>
        {
            policy.RequireAuthenticatedUser();
            policy.RequireClaim("sub");
            policy.RequireAssertion(context =>
                context.User
                    .FindAll("scp")
                    .SelectMany(claim => claim.Value.Split(' ', StringSplitOptions.RemoveEmptyEntries))
                    .Contains("access_as_user", StringComparer.Ordinal)
            );
        }
    )
    .SetFallbackPolicy(
        new AuthorizationPolicyBuilder()
            .RequireAuthenticatedUser()
            .Build()
    );

var allowedOrigins = builder.Configuration
    .GetSection("Cors:AllowedOrigins")
    .Get<string[]>() ?? [];

builder.Services.AddCors(options =>
{
    options.AddPolicy("Frontend", policy =>
    {
        if (allowedOrigins.Length > 0)
        {
            policy
                .WithOrigins(allowedOrigins)
                .AllowAnyHeader()
                .AllowAnyMethod();
        }
    });
});

var app = builder.Build();

if ((app.Environment.IsStaging() || app.Environment.IsProduction())
    && app.Configuration.GetValue<bool>("Database:ApplyMigrationsOnStartup"))
{
    await using var scope = app.Services.CreateAsyncScope();
    var db = scope.ServiceProvider.GetRequiredService<PlannerDbContext>();
    var logger = scope.ServiceProvider
        .GetRequiredService<ILoggerFactory>()
        .CreateLogger("DatabaseMigration");
    var environmentName = app.Environment.EnvironmentName;

    ApplyingDatabaseMigrations(logger, environmentName);

    await db.Database.MigrateAsync();

    DatabaseMigrationsApplied(logger, environmentName);
}

app.UseExceptionHandler();
app.UseCors("Frontend");
app.UseAuthentication();
app.UseAuthorization();
app.UseFastEndpoints(options =>
{
    options.Endpoints.RoutePrefix = "api/v1";

    // Every endpoint defaults to the authenticated AccessAsUser policy; public endpoints (e.g. the static
    // game-catalog data) opt out with AllowAnonymous() in their own Configure(), which the authorization
    // middleware honours over the applied policy.
    //
    // CurrentUserPreProcessor also runs for every endpoint (including anonymous ones — it no-ops when the
    // request isn't authenticated), resolving the caller's iss/sub claims and Account/Profile ids exactly
    // once per request into CurrentUserState, instead of every endpoint re-deriving them itself.
    options.Endpoints.Configurator = endpoint =>
    {
        endpoint.Policies(AuthorizationPolicies.AccessAsUser);
        endpoint.PreProcessor<CurrentUserPreProcessor>(Order.Before);
    };
});

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi("/openapi/{documentName}.json").AllowAnonymous();
    app.MapScalarApiReference("/docs", options =>
    {
        options.WithTitle("Tacticus Planner API");
        options.WithOpenApiRoutePattern("/openapi/{documentName}.json");
    }).AllowAnonymous();
}

app.MapDefaultEndpoints();

// Eagerly load + validate the embedded game catalog at startup so bad data fails fast (rather than on the
// first catalog request).
_ = app.Services.GetRequiredService<IGameCatalogProvider>();

app.Run();

public partial class Program
{
    [LoggerMessage(
        EventId = 2,
        Level = LogLevel.Information,
        Message = "Applying database migrations for {EnvironmentName}."
    )]
    private static partial void ApplyingDatabaseMigrations(ILogger logger, string environmentName);

    [LoggerMessage(
        EventId = 3,
        Level = LogLevel.Information,
        Message = "Database migrations applied for {EnvironmentName}."
    )]
    private static partial void DatabaseMigrationsApplied(ILogger logger, string environmentName);

}
