// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TacticusPlanner.Api.Persistence;

#nullable disable

namespace TacticusPlanner.Api.Persistence.Migrations
{
    [DbContext(typeof(PlannerDbContext))]
    partial class PlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TacticusPlanner.Api.Persistence.Users.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("accounts", "identity");
                });

            modelBuilder.Entity("TacticusPlanner.Api.Persistence.Users.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("TacticusUserId")
                        .HasColumnType("text")
                        .HasColumnName("tacticus_user_id");

                    b.Property<byte[]>("TacticusUserIdHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("tacticus_user_id_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("TacticusUserIdHash")
                        .IsUnique()
                        .HasFilter("tacticus_user_id_hash IS NOT NULL");

                    b.ToTable("profiles", "player");
                });

            modelBuilder.Entity("TacticusPlanner.Api.Persistence.Users.TacticusIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TacticusApiKey")
                        .HasColumnType("text")
                        .HasColumnName("tacticus_api_key");

                    b.Property<DateTimeOffset?>("TacticusSourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tacticus_source_updated_at");

                    b.Property<DateTimeOffset?>("TacticusSyncLastAttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tacticus_sync_last_attempted_at");

                    b.Property<string>("TacticusSyncLastResultCode")
                        .HasColumnType("text")
                        .HasColumnName("tacticus_sync_last_result_code");

                    b.Property<DateTimeOffset?>("TacticusSyncLastSucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tacticus_sync_last_succeeded_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tacticus_integrations", "integration");
                });

            modelBuilder.Entity("TacticusPlanner.Api.Persistence.Users.Profile", b =>
                {
                    b.HasOne("TacticusPlanner.Api.Persistence.Users.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("TacticusPlanner.Api.Persistence.Users.Profile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TacticusPlanner.Api.Persistence.Users.TacticusIntegration", b =>
                {
                    b.HasOne("TacticusPlanner.Api.Persistence.Users.Profile", "Profile")
                        .WithOne("TacticusIntegration")
                        .HasForeignKey("TacticusPlanner.Api.Persistence.Users.TacticusIntegration", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TacticusPlanner.Api.Persistence.Users.Account", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TacticusPlanner.Api.Persistence.Users.Profile", b =>
                {
                    b.Navigation("TacticusIntegration");
                });
#pragma warning restore 612, 618
        }
    }
}
