// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TacticusPlanner.Persistence;

#nullable disable

namespace TacticusPlanner.Persistence.Migrations
{
    [DbContext(typeof(PlannerDbContext))]
    [Migration("20260721210838_AddCampaignEventProgress")]
    partial class AddCampaignEventProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TacticusPlanner.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Goals.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<List<Guid>>("DependsOn")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("depends_on");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("goal_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileId", "EntityType", "EntityId", "GoalType")
                        .IsUnique()
                        .HasDatabaseName("ix_goals_one_active_or_paused_per_entity_and_type")
                        .HasFilter("status IN ('Active', 'Paused')");

                    b.ToTable("goals", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Guilds.Guild", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConfiguredByProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("configured_by_profile_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GuildApiToken")
                        .HasColumnType("text")
                        .HasColumnName("guild_api_token");

                    b.Property<DateTimeOffset?>("LastSyncAttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_attempted_at");

                    b.Property<DateTimeOffset?>("LastSyncSucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_succeeded_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("TacticusGuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tacticus_guild_id");

                    b.Property<byte[]>("TacticusGuildIdHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("tacticus_guild_id_hash");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguredByProfileId");

                    b.HasIndex("TacticusGuildIdHash")
                        .IsUnique()
                        .HasFilter("tacticus_guild_id_hash IS NOT NULL");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("guilds", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Guilds.GuildMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid")
                        .HasColumnName("guild_id");

                    b.Property<long?>("LastActiveInGameOn")
                        .HasColumnType("bigint")
                        .HasColumnName("last_active_in_game_on");

                    b.Property<DateTimeOffset?>("LastActiveInPlannerOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_in_planner_on");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("LinkedPlayerName")
                        .HasColumnType("text")
                        .HasColumnName("linked_player_name");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("TacticusUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tacticus_user_id");

                    b.Property<byte[]>("TacticusUserIdHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("tacticus_user_id_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique()
                        .HasFilter("profile_id IS NOT NULL");

                    b.HasIndex("GuildId", "TacticusUserIdHash")
                        .IsUnique();

                    b.ToTable("guild_members", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Planning.PlanningSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyEnergy")
                        .HasColumnType("integer")
                        .HasColumnName("daily_energy");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("planning_settings", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Domain.PlayerData.PlayerDataOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("player_data_overrides", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Domain.PlayerData.PlayerDataSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("ChunkHashes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("chunk_hashes");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_hash");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<long>("TacticusLastUpdatedOn")
                        .HasColumnType("bigint")
                        .HasColumnName("tacticus_last_updated_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("player_data_snapshots", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Profiles.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("ActiveProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_project_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("TacticusUserId")
                        .HasColumnType("text")
                        .HasColumnName("tacticus_user_id");

                    b.Property<byte[]>("TacticusUserIdHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("tacticus_user_id_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("TacticusUserIdHash")
                        .IsUnique()
                        .HasFilter("tacticus_user_id_hash IS NOT NULL");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Profiles.TacticusIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TacticusApiKey")
                        .HasColumnType("text")
                        .HasColumnName("tacticus_api_key");

                    b.Property<DateTimeOffset?>("TacticusSyncLastAttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tacticus_sync_last_attempted_at");

                    b.Property<DateTimeOffset?>("TacticusSyncLastSucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tacticus_sync_last_succeeded_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tacticus_integrations", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProfileId" }, "ix_projects_profile_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Projects.ProjectGoal", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.HasKey("ProjectId", "GoalId");

                    b.HasIndex("GoalId");

                    b.ToTable("project_goals", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Projects.ProjectTeam", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ProjectId", "TeamId");

                    b.ToTable("project_teams", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Goals.Goal", b =>
                {
                    b.HasOne("TacticusPlanner.Domain.Profiles.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TacticusPlanner.Domain.Goals.GoalConfig", "Config", b1 =>
                        {
                            b1.Property<Guid>("GoalId");

                            b1.PrimitiveCollection<string>("FarmingLocationIds");

                            b1.Property<int>("FarmingStrategy");

                            b1.HasKey("GoalId");

                            b1.ToTable("goals");

                            b1
                                .ToJson("config")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("GoalId");

                            b1.OwnsOne("TacticusPlanner.Domain.Goals.AbilityTarget", "Ability", b2 =>
                                {
                                    b2.Property<Guid>("GoalConfigGoalId");

                                    b2.Property<int>("ActiveEnd");

                                    b2.Property<int>("ActiveStart");

                                    b2.Property<int>("PassiveEnd");

                                    b2.Property<int>("PassiveStart");

                                    b2.HasKey("GoalConfigGoalId");

                                    b2.ToTable("goals");

                                    b2.WithOwner()
                                        .HasForeignKey("GoalConfigGoalId");
                                });

                            b1.OwnsOne("TacticusPlanner.Domain.Goals.AscensionFarmingConfig", "AscensionFarming", b2 =>
                                {
                                    b2.Property<Guid>("GoalConfigGoalId");

                                    b2.PrimitiveCollection<string>("MythicShardBattleIds")
                                        .IsRequired();

                                    b2.PrimitiveCollection<string>("ShardBattleIds")
                                        .IsRequired();

                                    b2.Property<int>("Source");

                                    b2.HasKey("GoalConfigGoalId");

                                    b2.ToTable("goals");

                                    b2.WithOwner()
                                        .HasForeignKey("GoalConfigGoalId");
                                });

                            b1.OwnsOne("TacticusPlanner.Domain.Goals.EquipmentTarget", "Equipment", b2 =>
                                {
                                    b2.Property<Guid>("GoalConfigGoalId");

                                    b2.Property<int>("TargetLevel");

                                    b2.HasKey("GoalConfigGoalId");

                                    b2.ToTable("goals");

                                    b2.WithOwner()
                                        .HasForeignKey("GoalConfigGoalId");
                                });

                            b1.OwnsOne("TacticusPlanner.Domain.Goals.LevelTarget", "Level", b2 =>
                                {
                                    b2.Property<Guid>("GoalConfigGoalId");

                                    b2.Property<int>("End");

                                    b2.Property<int>("Start");

                                    b2.HasKey("GoalConfigGoalId");

                                    b2.ToTable("goals");

                                    b2.WithOwner()
                                        .HasForeignKey("GoalConfigGoalId");
                                });

                            b1.OwnsOne("TacticusPlanner.Domain.Goals.ProgressionTarget", "Progression", b2 =>
                                {
                                    b2.Property<Guid>("GoalConfigGoalId");

                                    b2.Property<string>("End")
                                        .IsRequired();

                                    b2.Property<string>("Start")
                                        .IsRequired();

                                    b2.HasKey("GoalConfigGoalId");

                                    b2.ToTable("goals");

                                    b2.WithOwner()
                                        .HasForeignKey("GoalConfigGoalId");
                                });

                            b1.OwnsOne("TacticusPlanner.Domain.Goals.RankTarget", "Rank", b2 =>
                                {
                                    b2.Property<Guid>("GoalConfigGoalId");

                                    b2.Property<int>("End");

                                    b2.Property<int>("EndAppliedUpgrades");

                                    b2.Property<bool>("EndPointFive");

                                    b2.Property<int>("Start");

                                    b2.Property<int>("StartAppliedUpgrades");

                                    b2.Property<bool>("StartPointFive");

                                    b2.HasKey("GoalConfigGoalId");

                                    b2.ToTable("goals");

                                    b2.WithOwner()
                                        .HasForeignKey("GoalConfigGoalId");
                                });

                            b1.OwnsOne("TacticusPlanner.Domain.Goals.UpgradeTarget", "Upgrade", b2 =>
                                {
                                    b2.Property<Guid>("GoalConfigGoalId");

                                    b2.HasKey("GoalConfigGoalId");

                                    b2.ToTable("goals");

                                    b2.WithOwner()
                                        .HasForeignKey("GoalConfigGoalId");

                                    b2.OwnsMany("TacticusPlanner.Domain.Goals.UpgradeItemTarget", "Targets", b3 =>
                                        {
                                            b3.Property<Guid>("UpgradeTargetGoalConfigGoalId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<int>("Quantity");

                                            b3.Property<string>("UpgradeId")
                                                .IsRequired();

                                            b3.HasKey("UpgradeTargetGoalConfigGoalId", "__synthesizedOrdinal");

                                            b3.ToTable("goals");

                                            b3.WithOwner()
                                                .HasForeignKey("UpgradeTargetGoalConfigGoalId");
                                        });

                                    b2.Navigation("Targets");
                                });

                            b1.Navigation("Ability");

                            b1.Navigation("AscensionFarming");

                            b1.Navigation("Equipment");

                            b1.Navigation("Level");

                            b1.Navigation("Progression");

                            b1.Navigation("Rank");

                            b1.Navigation("Upgrade");
                        });

                    b.OwnsMany("TacticusPlanner.Domain.Goals.GoalEvent", "Events", b1 =>
                        {
                            b1.Property<Guid>("GoalId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTimeOffset>("At");

                            b1.Property<int>("Type");

                            b1.HasKey("GoalId", "__synthesizedOrdinal");

                            b1.ToTable("goals");

                            b1
                                .ToJson("events")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.OwnsMany("TacticusPlanner.Domain.Goals.GoalMilestone", "Milestones", b1 =>
                        {
                            b1.Property<Guid>("GoalId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTimeOffset?>("CompletedAt");

                            b1.Property<int>("Index");

                            b1.Property<string>("Kind")
                                .IsRequired();

                            b1.Property<string>("Source")
                                .IsRequired();

                            b1.Property<string>("Status")
                                .IsRequired();

                            b1.Property<string>("TargetState")
                                .IsRequired();

                            b1.HasKey("GoalId", "__synthesizedOrdinal");

                            b1.ToTable("goals");

                            b1
                                .ToJson("milestones")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.OwnsOne("TacticusPlanner.Domain.Goals.GoalSnapshot", "Snapshot", b1 =>
                        {
                            b1.Property<Guid>("GoalId");

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<int?>("InitialActiveAbilityLevel");

                            b1.Property<int?>("InitialPassiveAbilityLevel");

                            b1.Property<string>("InitialProgression");

                            b1.Property<string>("InitialRank");

                            b1.Property<bool?>("InitialUnlocked");

                            b1.Property<int?>("OriginalEnergyTotal");

                            b1.Property<DateTimeOffset?>("OriginalEstimateDate");

                            b1.Property<int?>("OriginalEstimateDays");

                            b1.Property<int?>("OriginalRaidsTotal");

                            b1.HasKey("GoalId");

                            b1.ToTable("goals");

                            b1
                                .ToJson("snapshot")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("GoalId");

                            b1.OwnsMany("TacticusPlanner.Domain.Goals.GoalSnapshotResource", "InitialInventoryContribution", b2 =>
                                {
                                    b2.Property<Guid>("GoalSnapshotGoalId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("Count");

                                    b2.Property<string>("ResourceId")
                                        .IsRequired();

                                    b2.HasKey("GoalSnapshotGoalId", "__synthesizedOrdinal");

                                    b2.ToTable("goals");

                                    b2.WithOwner()
                                        .HasForeignKey("GoalSnapshotGoalId");
                                });

                            b1.OwnsMany("TacticusPlanner.Domain.Goals.GoalSnapshotResource", "InitialRequirement", b2 =>
                                {
                                    b2.Property<Guid>("GoalSnapshotGoalId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("Count");

                                    b2.Property<string>("ResourceId")
                                        .IsRequired();

                                    b2.HasKey("GoalSnapshotGoalId", "__synthesizedOrdinal");

                                    b2.ToTable("goals");

                                    b2.WithOwner()
                                        .HasForeignKey("GoalSnapshotGoalId");
                                });

                            b1.Navigation("InitialInventoryContribution");

                            b1.Navigation("InitialRequirement");
                        });

                    b.Navigation("Config")
                        .IsRequired();

                    b.Navigation("Events");

                    b.Navigation("Milestones");

                    b.Navigation("Profile");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Guilds.Guild", b =>
                {
                    b.HasOne("TacticusPlanner.Domain.Profiles.Profile", "ConfiguredByProfile")
                        .WithMany()
                        .HasForeignKey("ConfiguredByProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConfiguredByProfile");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Guilds.GuildMember", b =>
                {
                    b.HasOne("TacticusPlanner.Domain.Guilds.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TacticusPlanner.Domain.Profiles.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Guild");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Planning.PlanningSettings", b =>
                {
                    b.HasOne("TacticusPlanner.Domain.Profiles.Profile", "Profile")
                        .WithOne("PlanningSettings")
                        .HasForeignKey("TacticusPlanner.Domain.Planning.PlanningSettings", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.PlayerData.PlayerDataOverride", b =>
                {
                    b.HasOne("TacticusPlanner.Domain.Profiles.Profile", "Profile")
                        .WithOne("PlayerDataOverride")
                        .HasForeignKey("TacticusPlanner.Domain.PlayerData.PlayerDataOverride", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TacticusPlanner.Domain.PlayerData.BattleResultOverrideRecord", "BattleResultOverrides", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataOverrideId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("BattleIndex");

                            b1.Property<bool>("LightningVictory");

                            b1.Property<int>("Medal");

                            b1.Property<string>("TacticusCampaignId")
                                .IsRequired();

                            b1.Property<bool?>("VictoryWithoutBorrowed");

                            b1.HasKey("PlayerDataOverrideId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_overrides");

                            b1
                                .ToJson("battle_result_overrides")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataOverrideId");
                        });

                    b.OwnsMany("TacticusPlanner.Domain.PlayerData.CampaignEventProgressOverrideRecord", "CampaignEventProgressOverrides", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataOverrideId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("CampaignGroupId")
                                .IsRequired();

                            b1.Property<int?>("CompletedBattleCount");

                            b1.PrimitiveCollection<string>("CompletedChallengeBattlesIds");

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("PlayerDataOverrideId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_overrides");

                            b1
                                .ToJson("campaign_event_progress_overrides")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataOverrideId");
                        });

                    b.OwnsMany("TacticusPlanner.Domain.PlayerData.OnslaughtProgressOverrideRecord", "OnslaughtProgressOverrides", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataOverrideId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Alliance")
                                .IsRequired();

                            b1.Property<string>("Sector")
                                .IsRequired();

                            b1.Property<int>("Tier");

                            b1.HasKey("PlayerDataOverrideId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_overrides");

                            b1
                                .ToJson("onslaught_progress_overrides")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataOverrideId");
                        });

                    b.Navigation("BattleResultOverrides");

                    b.Navigation("CampaignEventProgressOverrides");

                    b.Navigation("OnslaughtProgressOverrides");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.PlayerData.PlayerDataSnapshot", b =>
                {
                    b.HasOne("TacticusPlanner.Domain.Profiles.Profile", "Profile")
                        .WithOne("PlayerDataSnapshot")
                        .HasForeignKey("TacticusPlanner.Domain.PlayerData.PlayerDataSnapshot", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.CampaignEventProgressRecord", "CampaignEventsProgress", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("CompletedBattleCount");

                            b1.PrimitiveCollection<string>("CompletedChallengeBattlesIds")
                                .IsRequired();

                            b1.Property<string>("TacticusCampaignId")
                                .IsRequired();

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("campaign_events_progress")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");
                        });

                    b.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.CampaignProgressRecord", "CampaignProgress", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("HighestCompletedBattleIndex");

                            b1.Property<string>("TacticusCampaignId")
                                .IsRequired();

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("campaign_progress")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");
                        });

                    b.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.InventoryChunk", "Inventory", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("RequisitionOrdersBlessed");

                            b1.Property<int>("RequisitionOrdersRegular");

                            b1.Property<int>("ResetStones");

                            b1.HasKey("PlayerDataSnapshotId");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("inventory")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");

                            b1.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.PlayerRarityAmountRecord", "ForgeBadges", b2 =>
                                {
                                    b2.Property<Guid>("InventoryChunkPlayerDataSnapshotId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<long>("Amount");

                                    b2.Property<string>("Rarity")
                                        .IsRequired();

                                    b2.HasKey("InventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryChunkPlayerDataSnapshotId");
                                });

                            b1.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.InventoryXpBookRecord", "XpBooks", b2 =>
                                {
                                    b2.Property<Guid>("InventoryChunkPlayerDataSnapshotId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<long>("Amount");

                                    b2.Property<string>("XpBookId")
                                        .IsRequired();

                                    b2.HasKey("InventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryChunkPlayerDataSnapshotId");
                                });

                            b1.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.MowComponentsRecord", "Components", b2 =>
                                {
                                    b2.Property<Guid>("InventoryChunkPlayerDataSnapshotId");

                                    b2.HasKey("InventoryChunkPlayerDataSnapshotId");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryChunkPlayerDataSnapshotId");

                                    b2.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.ComponentAmountRecord", "Chaos", b3 =>
                                        {
                                            b3.Property<Guid>("MowComponentsRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<long>("Amount");

                                            b3.HasKey("MowComponentsRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("MowComponentsRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.ComponentAmountRecord", "Imperial", b3 =>
                                        {
                                            b3.Property<Guid>("MowComponentsRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<long>("Amount");

                                            b3.HasKey("MowComponentsRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("MowComponentsRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.ComponentAmountRecord", "Xenos", b3 =>
                                        {
                                            b3.Property<Guid>("MowComponentsRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<long>("Amount");

                                            b3.HasKey("MowComponentsRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("MowComponentsRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.Navigation("Chaos")
                                        .IsRequired();

                                    b2.Navigation("Imperial")
                                        .IsRequired();

                                    b2.Navigation("Xenos")
                                        .IsRequired();
                                });

                            b1.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.PlayerAbilityBadgesRecord", "AbilityBadges", b2 =>
                                {
                                    b2.Property<Guid>("InventoryChunkPlayerDataSnapshotId");

                                    b2.HasKey("InventoryChunkPlayerDataSnapshotId");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryChunkPlayerDataSnapshotId");

                                    b2.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.PlayerRarityAmountRecord", "Chaos", b3 =>
                                        {
                                            b3.Property<Guid>("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<long>("Amount");

                                            b3.Property<string>("Rarity")
                                                .IsRequired();

                                            b3.HasKey("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.PlayerRarityAmountRecord", "Imperial", b3 =>
                                        {
                                            b3.Property<Guid>("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<long>("Amount");

                                            b3.Property<string>("Rarity")
                                                .IsRequired();

                                            b3.HasKey("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.PlayerRarityAmountRecord", "Xenos", b3 =>
                                        {
                                            b3.Property<Guid>("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<long>("Amount");

                                            b3.Property<string>("Rarity")
                                                .IsRequired();

                                            b3.HasKey("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.Navigation("Chaos");

                                    b2.Navigation("Imperial");

                                    b2.Navigation("Xenos");
                                });

                            b1.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.PlayerOrbsRecord", "Orbs", b2 =>
                                {
                                    b2.Property<Guid>("InventoryChunkPlayerDataSnapshotId");

                                    b2.HasKey("InventoryChunkPlayerDataSnapshotId");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryChunkPlayerDataSnapshotId");

                                    b2.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.PlayerRarityAmountRecord", "Chaos", b3 =>
                                        {
                                            b3.Property<Guid>("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<long>("Amount");

                                            b3.Property<string>("Rarity")
                                                .IsRequired();

                                            b3.HasKey("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.PlayerRarityAmountRecord", "Imperial", b3 =>
                                        {
                                            b3.Property<Guid>("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<long>("Amount");

                                            b3.Property<string>("Rarity")
                                                .IsRequired();

                                            b3.HasKey("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.PlayerRarityAmountRecord", "Xenos", b3 =>
                                        {
                                            b3.Property<Guid>("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<long>("Amount");

                                            b3.Property<string>("Rarity")
                                                .IsRequired();

                                            b3.HasKey("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.Navigation("Chaos");

                                    b2.Navigation("Imperial");

                                    b2.Navigation("Xenos");
                                });

                            b1.Navigation("AbilityBadges")
                                .IsRequired();

                            b1.Navigation("Components")
                                .IsRequired();

                            b1.Navigation("ForgeBadges");

                            b1.Navigation("Orbs")
                                .IsRequired();

                            b1.Navigation("XpBooks");
                        });

                    b.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.InventoryItemRecord", "InventoryItems", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<long>("Amount");

                            b1.Property<string>("ItemId")
                                .IsRequired();

                            b1.Property<int>("Level");

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("inventory_items")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");
                        });

                    b.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.InventoryShardRecord", "InventoryShards", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<long>("Amount");

                            b1.Property<long>("MythicAmount");

                            b1.Property<string>("UnitId")
                                .IsRequired();

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("inventory_shards")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");
                        });

                    b.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.InventoryUpgradeRecord", "InventoryUpgrades", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<long>("Amount");

                            b1.Property<string>("UpgradeId")
                                .IsRequired();

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("inventory_upgrades")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");
                        });

                    b.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.LiveProgressChunk", "LiveProgress", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<string>("ActiveCampaignEventId");

                            b1.HasKey("PlayerDataSnapshotId");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("live_progress")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");

                            b1.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.BattleAttemptRecord", "BattleAttempts", b2 =>
                                {
                                    b2.Property<Guid>("LiveProgressChunkPlayerDataSnapshotId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("AttemptsLeft");

                                    b2.Property<int>("AttemptsUsed");

                                    b2.Property<int>("BattleIndex");

                                    b2.Property<string>("TacticusCampaignId")
                                        .IsRequired();

                                    b2.HasKey("LiveProgressChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("LiveProgressChunkPlayerDataSnapshotId");
                                });

                            b1.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.GameModeTokensChunk", "GameModeTokens", b2 =>
                                {
                                    b2.Property<Guid>("LiveProgressChunkPlayerDataSnapshotId");

                                    b2.HasKey("LiveProgressChunkPlayerDataSnapshotId");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("LiveProgressChunkPlayerDataSnapshotId");

                                    b2.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.TokenBucketRecord", "Arena", b3 =>
                                        {
                                            b3.Property<Guid>("GameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");

                                            b3.Property<int>("Current");

                                            b3.Property<int>("Max");

                                            b3.Property<int>("NextTokenInSeconds");

                                            b3.Property<int>("RegenDelayInSeconds");

                                            b3.HasKey("GameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("GameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.TokenBucketRecord", "Onslaught", b3 =>
                                        {
                                            b3.Property<Guid>("GameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");

                                            b3.Property<int>("Current");

                                            b3.Property<int>("Max");

                                            b3.Property<int>("NextTokenInSeconds");

                                            b3.Property<int>("RegenDelayInSeconds");

                                            b3.HasKey("GameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("GameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.TokenBucketRecord", "SalvageRun", b3 =>
                                        {
                                            b3.Property<Guid>("GameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");

                                            b3.Property<int>("Current");

                                            b3.Property<int>("Max");

                                            b3.Property<int>("NextTokenInSeconds");

                                            b3.Property<int>("RegenDelayInSeconds");

                                            b3.HasKey("GameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("GameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.GuildRaidTokensRecord", "GuildRaid", b3 =>
                                        {
                                            b3.Property<Guid>("GameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");

                                            b3.HasKey("GameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("GameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");

                                            b3.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.TokenBucketRecord", "BombTokens", b4 =>
                                                {
                                                    b4.Property<Guid>("GuildRaidTokensRecordGameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId")
                                                        .HasColumnName("GuildRaidTokensRecordGameModeTokensChunkLiveProgressChunkPlaye~");

                                                    b4.Property<int>("Current");

                                                    b4.Property<int>("Max");

                                                    b4.Property<int>("NextTokenInSeconds");

                                                    b4.Property<int>("RegenDelayInSeconds");

                                                    b4.HasKey("GuildRaidTokensRecordGameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");

                                                    b4.ToTable("player_data_snapshots");

                                                    b4.WithOwner()
                                                        .HasForeignKey("GuildRaidTokensRecordGameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");
                                                });

                                            b3.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.TokenBucketRecord", "Tokens", b4 =>
                                                {
                                                    b4.Property<Guid>("GuildRaidTokensRecordGameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId")
                                                        .HasColumnName("GuildRaidTokensRecordGameModeTokensChunkLiveProgressChunkPlaye~");

                                                    b4.Property<int>("Current");

                                                    b4.Property<int>("Max");

                                                    b4.Property<int>("NextTokenInSeconds");

                                                    b4.Property<int>("RegenDelayInSeconds");

                                                    b4.HasKey("GuildRaidTokensRecordGameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");

                                                    b4.ToTable("player_data_snapshots");

                                                    b4.WithOwner()
                                                        .HasForeignKey("GuildRaidTokensRecordGameModeTokensChunkLiveProgressChunkPlayerDataSnapshotId");
                                                });

                                            b3.Navigation("BombTokens")
                                                .IsRequired();

                                            b3.Navigation("Tokens")
                                                .IsRequired();
                                        });

                                    b2.Navigation("Arena");

                                    b2.Navigation("GuildRaid");

                                    b2.Navigation("Onslaught");

                                    b2.Navigation("SalvageRun");
                                });

                            b1.Navigation("BattleAttempts");

                            b1.Navigation("GameModeTokens")
                                .IsRequired();
                        });

                    b.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.LreProgressRecord", "LreProgress", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("CurrentClaimedChestIndex");

                            b1.Property<int>("CurrentCurrency");

                            b1.Property<int?>("CurrentEventRun");

                            b1.Property<int>("CurrentPoints");

                            b1.Property<int>("CurrentShards");

                            b1.Property<int?>("ExtraCurrencyPerPayout");

                            b1.Property<bool?>("HasUsedAdForExtraTokenToday");

                            b1.Property<string>("Id")
                                .IsRequired();

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("lre_progress")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");

                            b1.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.LreTrackProgressRecord", "Alpha", b2 =>
                                {
                                    b2.Property<Guid>("LreProgressRecordPlayerDataSnapshotId");

                                    b2.Property<int>("LreProgressRecord__synthesizedOrdinal");

                                    b2.HasKey("LreProgressRecordPlayerDataSnapshotId", "LreProgressRecord__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("LreProgressRecordPlayerDataSnapshotId", "LreProgressRecord__synthesizedOrdinal");

                                    b2.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.LreEncounterProgressRecord", "Encounters", b3 =>
                                        {
                                            b3.Property<Guid>("LreTrackProgressRecordLreProgressRecordPlayerDataSnapshotId");

                                            b3.Property<int>("LreTrackProgressRecordLreProgressRecord__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<int>("EncounterPoints");

                                            b3.Property<int>("HighScore");

                                            b3.PrimitiveCollection<string>("ObjectivesCleared")
                                                .IsRequired();

                                            b3.HasKey("LreTrackProgressRecordLreProgressRecordPlayerDataSnapshotId", "LreTrackProgressRecordLreProgressRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("LreTrackProgressRecordLreProgressRecordPlayerDataSnapshotId", "LreTrackProgressRecordLreProgressRecord__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Encounters");
                                });

                            b1.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.LreTrackProgressRecord", "Beta", b2 =>
                                {
                                    b2.Property<Guid>("LreProgressRecordPlayerDataSnapshotId");

                                    b2.Property<int>("LreProgressRecord__synthesizedOrdinal");

                                    b2.HasKey("LreProgressRecordPlayerDataSnapshotId", "LreProgressRecord__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("LreProgressRecordPlayerDataSnapshotId", "LreProgressRecord__synthesizedOrdinal");

                                    b2.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.LreEncounterProgressRecord", "Encounters", b3 =>
                                        {
                                            b3.Property<Guid>("LreTrackProgressRecordLreProgressRecordPlayerDataSnapshotId");

                                            b3.Property<int>("LreTrackProgressRecordLreProgressRecord__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<int>("EncounterPoints");

                                            b3.Property<int>("HighScore");

                                            b3.PrimitiveCollection<string>("ObjectivesCleared")
                                                .IsRequired();

                                            b3.HasKey("LreTrackProgressRecordLreProgressRecordPlayerDataSnapshotId", "LreTrackProgressRecordLreProgressRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("LreTrackProgressRecordLreProgressRecordPlayerDataSnapshotId", "LreTrackProgressRecordLreProgressRecord__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Encounters");
                                });

                            b1.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.TokenBucketRecord", "CurrentEventTokens", b2 =>
                                {
                                    b2.Property<Guid>("LreProgressRecordPlayerDataSnapshotId");

                                    b2.Property<int>("LreProgressRecord__synthesizedOrdinal");

                                    b2.Property<int>("Current");

                                    b2.Property<int>("Max");

                                    b2.Property<int>("NextTokenInSeconds");

                                    b2.Property<int>("RegenDelayInSeconds");

                                    b2.HasKey("LreProgressRecordPlayerDataSnapshotId", "LreProgressRecord__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("LreProgressRecordPlayerDataSnapshotId", "LreProgressRecord__synthesizedOrdinal");
                                });

                            b1.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.LreTrackProgressRecord", "Gamma", b2 =>
                                {
                                    b2.Property<Guid>("LreProgressRecordPlayerDataSnapshotId");

                                    b2.Property<int>("LreProgressRecord__synthesizedOrdinal");

                                    b2.HasKey("LreProgressRecordPlayerDataSnapshotId", "LreProgressRecord__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("LreProgressRecordPlayerDataSnapshotId", "LreProgressRecord__synthesizedOrdinal");

                                    b2.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.LreEncounterProgressRecord", "Encounters", b3 =>
                                        {
                                            b3.Property<Guid>("LreTrackProgressRecordLreProgressRecordPlayerDataSnapshotId");

                                            b3.Property<int>("LreTrackProgressRecordLreProgressRecord__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<int>("EncounterPoints");

                                            b3.Property<int>("HighScore");

                                            b3.PrimitiveCollection<string>("ObjectivesCleared")
                                                .IsRequired();

                                            b3.HasKey("LreTrackProgressRecordLreProgressRecordPlayerDataSnapshotId", "LreTrackProgressRecordLreProgressRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("LreTrackProgressRecordLreProgressRecordPlayerDataSnapshotId", "LreTrackProgressRecordLreProgressRecord__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Encounters");
                                });

                            b1.Navigation("Alpha");

                            b1.Navigation("Beta");

                            b1.Navigation("CurrentEventTokens");

                            b1.Navigation("Gamma");
                        });

                    b.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.PlayerCharacterRecord", "Characters", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.PrimitiveCollection<string>("AppliedUpgradeSlots")
                                .IsRequired();

                            b1.Property<long>("MythicShards");

                            b1.Property<int>("ProgressionIndex");

                            b1.Property<int>("Rank");

                            b1.Property<long>("Shards");

                            b1.Property<string>("UnitId")
                                .IsRequired();

                            b1.Property<long>("Xp");

                            b1.Property<int>("XpLevel");

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("characters")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");

                            b1.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.PlayerUnitAbilityRecord", "Abilities", b2 =>
                                {
                                    b2.Property<Guid>("PlayerCharacterRecordPlayerDataSnapshotId");

                                    b2.Property<int>("PlayerCharacterRecord__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("AbilityId")
                                        .IsRequired();

                                    b2.Property<int>("Level");

                                    b2.HasKey("PlayerCharacterRecordPlayerDataSnapshotId", "PlayerCharacterRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerCharacterRecordPlayerDataSnapshotId", "PlayerCharacterRecord__synthesizedOrdinal");
                                });

                            b1.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.PlayerUnitEquipmentSlotRecord", "EquippedItems", b2 =>
                                {
                                    b2.Property<Guid>("PlayerCharacterRecordPlayerDataSnapshotId");

                                    b2.Property<int>("PlayerCharacterRecord__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("EquipmentId")
                                        .IsRequired();

                                    b2.Property<int>("Level");

                                    b2.Property<string>("SlotId")
                                        .IsRequired();

                                    b2.HasKey("PlayerCharacterRecordPlayerDataSnapshotId", "PlayerCharacterRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerCharacterRecordPlayerDataSnapshotId", "PlayerCharacterRecord__synthesizedOrdinal");
                                });

                            b1.Navigation("Abilities");

                            b1.Navigation("EquippedItems");
                        });

                    b.OwnsOne("TacticusPlanner.Domain.PlayerData.Chunks.PlayerDetailsChunk", "PlayerDetails", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("PowerLevel");

                            b1.HasKey("PlayerDataSnapshotId");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("player_details")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");
                        });

                    b.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.PlayerMowRecord", "Mows", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.PrimitiveCollection<string>("AppliedUpgradeSlots")
                                .IsRequired();

                            b1.Property<long>("MythicShards");

                            b1.Property<int>("ProgressionIndex");

                            b1.Property<long>("Shards");

                            b1.Property<string>("UnitId")
                                .IsRequired();

                            b1.Property<long>("Xp");

                            b1.Property<int>("XpLevel");

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("mows")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");

                            b1.OwnsMany("TacticusPlanner.Domain.PlayerData.Chunks.PlayerUnitAbilityRecord", "Abilities", b2 =>
                                {
                                    b2.Property<Guid>("PlayerMowRecordPlayerDataSnapshotId");

                                    b2.Property<int>("PlayerMowRecord__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("AbilityId")
                                        .IsRequired();

                                    b2.Property<int>("Level");

                                    b2.HasKey("PlayerMowRecordPlayerDataSnapshotId", "PlayerMowRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerMowRecordPlayerDataSnapshotId", "PlayerMowRecord__synthesizedOrdinal");
                                });

                            b1.Navigation("Abilities");
                        });

                    b.Navigation("CampaignEventsProgress");

                    b.Navigation("CampaignProgress");

                    b.Navigation("Characters");

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("InventoryItems");

                    b.Navigation("InventoryShards");

                    b.Navigation("InventoryUpgrades");

                    b.Navigation("LiveProgress")
                        .IsRequired();

                    b.Navigation("LreProgress");

                    b.Navigation("Mows");

                    b.Navigation("PlayerDetails")
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Profiles.Profile", b =>
                {
                    b.HasOne("TacticusPlanner.Domain.Accounts.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("TacticusPlanner.Domain.Profiles.Profile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Profiles.TacticusIntegration", b =>
                {
                    b.HasOne("TacticusPlanner.Domain.Profiles.Profile", "Profile")
                        .WithOne("TacticusIntegration")
                        .HasForeignKey("TacticusPlanner.Domain.Profiles.TacticusIntegration", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Projects.Project", b =>
                {
                    b.HasOne("TacticusPlanner.Domain.Profiles.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Projects.ProjectGoal", b =>
                {
                    b.HasOne("TacticusPlanner.Domain.Goals.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TacticusPlanner.Domain.Projects.Project", "Project")
                        .WithMany("ProjectGoals")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Projects.ProjectTeam", b =>
                {
                    b.HasOne("TacticusPlanner.Domain.Projects.Project", "Project")
                        .WithMany("ProjectTeams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Accounts.Account", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Guilds.Guild", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Profiles.Profile", b =>
                {
                    b.Navigation("PlanningSettings");

                    b.Navigation("PlayerDataOverride");

                    b.Navigation("PlayerDataSnapshot");

                    b.Navigation("TacticusIntegration");
                });

            modelBuilder.Entity("TacticusPlanner.Domain.Projects.Project", b =>
                {
                    b.Navigation("ProjectGoals");

                    b.Navigation("ProjectTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
