// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TacticusPlanner.Persistence;

#nullable disable

namespace TacticusPlanner.Persistence.Migrations
{
    [DbContext(typeof(PlannerDbContext))]
    [Migration("20260706161748_AddPlayerData")]
    partial class AddPlayerData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TacticusPlanner.Persistence.Users.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Persistence.Users.PlayerData.PlayerDataOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("player_data_overrides", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Persistence.Users.PlayerData.PlayerDataSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("ChunkHashes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("chunk_hashes");

                    b.Property<string>("ConfigHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_hash");

                    b.Property<DateTimeOffset>("SyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at");

                    b.Property<long>("TacticusLastUpdatedOn")
                        .HasColumnType("bigint")
                        .HasColumnName("tacticus_last_updated_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("player_data_snapshots", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Persistence.Users.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("TacticusUserId")
                        .HasColumnType("text")
                        .HasColumnName("tacticus_user_id");

                    b.Property<byte[]>("TacticusUserIdHash")
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("tacticus_user_id_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("TacticusUserIdHash")
                        .IsUnique()
                        .HasFilter("tacticus_user_id_hash IS NOT NULL");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Persistence.Users.TacticusIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TacticusApiKey")
                        .HasColumnType("text")
                        .HasColumnName("tacticus_api_key");

                    b.Property<DateTimeOffset?>("TacticusSyncLastAttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tacticus_sync_last_attempted_at");

                    b.Property<DateTimeOffset?>("TacticusSyncLastSucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("tacticus_sync_last_succeeded_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tacticus_integrations", (string)null);
                });

            modelBuilder.Entity("TacticusPlanner.Persistence.Users.PlayerData.PlayerDataOverride", b =>
                {
                    b.HasOne("TacticusPlanner.Persistence.Users.Profile", "Profile")
                        .WithOne("PlayerDataOverride")
                        .HasForeignKey("TacticusPlanner.Persistence.Users.PlayerData.PlayerDataOverride", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.BattleResultOverrideRecord", "BattleResultOverrides", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataOverrideId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("BattleIndex");

                            b1.Property<bool>("LightningVictory");

                            b1.Property<int>("Medal");

                            b1.Property<string>("TacticusCampaignId")
                                .IsRequired();

                            b1.Property<bool?>("VictoryWithoutBorrowed");

                            b1.HasKey("PlayerDataOverrideId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_overrides");

                            b1
                                .ToJson("battle_result_overrides")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataOverrideId");
                        });

                    b.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.CampaignProgressOverrideRecord", "CampaignProgressOverrides", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataOverrideId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("CatalogCampaignGroupId")
                                .IsRequired();

                            b1.Property<int>("HighestCompletedNodeNumber");

                            b1.HasKey("PlayerDataOverrideId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_overrides");

                            b1
                                .ToJson("campaign_progress_overrides")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataOverrideId");
                        });

                    b.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.LreOverrideRecord", "LreOverrides", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataOverrideId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Annotation")
                                .IsRequired();

                            b1.Property<int>("EncounterIndex");

                            b1.Property<string>("EventId")
                                .IsRequired();

                            b1.Property<int>("LaneId");

                            b1.HasKey("PlayerDataOverrideId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_overrides");

                            b1
                                .ToJson("lre_overrides")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataOverrideId");
                        });

                    b.Navigation("BattleResultOverrides");

                    b.Navigation("CampaignProgressOverrides");

                    b.Navigation("LreOverrides");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TacticusPlanner.Persistence.Users.PlayerData.PlayerDataSnapshot", b =>
                {
                    b.HasOne("TacticusPlanner.Persistence.Users.Profile", "Profile")
                        .WithOne("PlayerDataSnapshot")
                        .HasForeignKey("TacticusPlanner.Persistence.Users.PlayerData.PlayerDataSnapshot", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TacticusPlanner.Persistence.Users.PlayerData.GameModeTokensChunk", "GameModeTokens", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.HasKey("PlayerDataSnapshotId");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("game_mode_tokens")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");

                            b1.OwnsOne("TacticusPlanner.Persistence.Users.PlayerData.TokenBucketRecord", "Arena", b2 =>
                                {
                                    b2.Property<Guid>("GameModeTokensChunkPlayerDataSnapshotId");

                                    b2.Property<int>("Current");

                                    b2.Property<int>("Max");

                                    b2.Property<int>("NextTokenInSeconds");

                                    b2.Property<int>("RegenDelayInSeconds");

                                    b2.HasKey("GameModeTokensChunkPlayerDataSnapshotId");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("GameModeTokensChunkPlayerDataSnapshotId");
                                });

                            b1.OwnsOne("TacticusPlanner.Persistence.Users.PlayerData.TokenBucketRecord", "Onslaught", b2 =>
                                {
                                    b2.Property<Guid>("GameModeTokensChunkPlayerDataSnapshotId");

                                    b2.Property<int>("Current");

                                    b2.Property<int>("Max");

                                    b2.Property<int>("NextTokenInSeconds");

                                    b2.Property<int>("RegenDelayInSeconds");

                                    b2.HasKey("GameModeTokensChunkPlayerDataSnapshotId");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("GameModeTokensChunkPlayerDataSnapshotId");
                                });

                            b1.OwnsOne("TacticusPlanner.Persistence.Users.PlayerData.TokenBucketRecord", "SalvageRun", b2 =>
                                {
                                    b2.Property<Guid>("GameModeTokensChunkPlayerDataSnapshotId");

                                    b2.Property<int>("Current");

                                    b2.Property<int>("Max");

                                    b2.Property<int>("NextTokenInSeconds");

                                    b2.Property<int>("RegenDelayInSeconds");

                                    b2.HasKey("GameModeTokensChunkPlayerDataSnapshotId");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("GameModeTokensChunkPlayerDataSnapshotId");
                                });

                            b1.OwnsOne("TacticusPlanner.Persistence.Users.PlayerData.GuildRaidTokensRecord", "GuildRaid", b2 =>
                                {
                                    b2.Property<Guid>("GameModeTokensChunkPlayerDataSnapshotId");

                                    b2.HasKey("GameModeTokensChunkPlayerDataSnapshotId");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("GameModeTokensChunkPlayerDataSnapshotId");

                                    b2.OwnsOne("TacticusPlanner.Persistence.Users.PlayerData.TokenBucketRecord", "BombTokens", b3 =>
                                        {
                                            b3.Property<Guid>("GuildRaidTokensRecordGameModeTokensChunkPlayerDataSnapshotId");

                                            b3.Property<int>("Current");

                                            b3.Property<int>("Max");

                                            b3.Property<int>("NextTokenInSeconds");

                                            b3.Property<int>("RegenDelayInSeconds");

                                            b3.HasKey("GuildRaidTokensRecordGameModeTokensChunkPlayerDataSnapshotId");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("GuildRaidTokensRecordGameModeTokensChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsOne("TacticusPlanner.Persistence.Users.PlayerData.TokenBucketRecord", "Tokens", b3 =>
                                        {
                                            b3.Property<Guid>("GuildRaidTokensRecordGameModeTokensChunkPlayerDataSnapshotId");

                                            b3.Property<int>("Current");

                                            b3.Property<int>("Max");

                                            b3.Property<int>("NextTokenInSeconds");

                                            b3.Property<int>("RegenDelayInSeconds");

                                            b3.HasKey("GuildRaidTokensRecordGameModeTokensChunkPlayerDataSnapshotId");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("GuildRaidTokensRecordGameModeTokensChunkPlayerDataSnapshotId");
                                        });

                                    b2.Navigation("BombTokens")
                                        .IsRequired();

                                    b2.Navigation("Tokens")
                                        .IsRequired();
                                });

                            b1.Navigation("Arena");

                            b1.Navigation("GuildRaid");

                            b1.Navigation("Onslaught");

                            b1.Navigation("SalvageRun");
                        });

                    b.OwnsOne("TacticusPlanner.Persistence.Users.PlayerData.InventoryChunk", "Inventory", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("RequisitionOrdersBlessed");

                            b1.Property<int>("RequisitionOrdersRegular");

                            b1.Property<int>("ResetStones");

                            b1.HasKey("PlayerDataSnapshotId");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("inventory")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");

                            b1.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerNamedRarityAmountRecord", "ForgeBadges", b2 =>
                                {
                                    b2.Property<Guid>("InventoryChunkPlayerDataSnapshotId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<long>("Amount");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Rarity")
                                        .IsRequired();

                                    b2.HasKey("InventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryChunkPlayerDataSnapshotId");
                                });

                            b1.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.InventoryShardRecord", "MythicShards", b2 =>
                                {
                                    b2.Property<Guid>("InventoryChunkPlayerDataSnapshotId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<long>("Amount");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("ShardId")
                                        .IsRequired();

                                    b2.HasKey("InventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryChunkPlayerDataSnapshotId");
                                });

                            b1.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.InventoryShardRecord", "Shards", b2 =>
                                {
                                    b2.Property<Guid>("InventoryChunkPlayerDataSnapshotId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<long>("Amount");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("ShardId")
                                        .IsRequired();

                                    b2.HasKey("InventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryChunkPlayerDataSnapshotId");
                                });

                            b1.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.InventoryXpBookRecord", "XpBooks", b2 =>
                                {
                                    b2.Property<Guid>("InventoryChunkPlayerDataSnapshotId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<long>("Amount");

                                    b2.Property<string>("Rarity")
                                        .IsRequired();

                                    b2.Property<string>("XpBookId")
                                        .IsRequired();

                                    b2.HasKey("InventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryChunkPlayerDataSnapshotId");
                                });

                            b1.OwnsOne("TacticusPlanner.Persistence.Users.PlayerData.PlayerAbilityBadgesRecord", "AbilityBadges", b2 =>
                                {
                                    b2.Property<Guid>("InventoryChunkPlayerDataSnapshotId");

                                    b2.HasKey("InventoryChunkPlayerDataSnapshotId");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryChunkPlayerDataSnapshotId");

                                    b2.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerNamedRarityAmountRecord", "Chaos", b3 =>
                                        {
                                            b3.Property<Guid>("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<long>("Amount");

                                            b3.Property<string>("Name")
                                                .IsRequired();

                                            b3.Property<string>("Rarity")
                                                .IsRequired();

                                            b3.HasKey("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerNamedRarityAmountRecord", "Imperial", b3 =>
                                        {
                                            b3.Property<Guid>("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<long>("Amount");

                                            b3.Property<string>("Name")
                                                .IsRequired();

                                            b3.Property<string>("Rarity")
                                                .IsRequired();

                                            b3.HasKey("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerNamedRarityAmountRecord", "Xenos", b3 =>
                                        {
                                            b3.Property<Guid>("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<long>("Amount");

                                            b3.Property<string>("Name")
                                                .IsRequired();

                                            b3.Property<string>("Rarity")
                                                .IsRequired();

                                            b3.HasKey("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("PlayerAbilityBadgesRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.Navigation("Chaos");

                                    b2.Navigation("Imperial");

                                    b2.Navigation("Xenos");
                                });

                            b1.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerMowComponentRecord", "Components", b2 =>
                                {
                                    b2.Property<Guid>("InventoryChunkPlayerDataSnapshotId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<long>("Amount");

                                    b2.Property<string>("GrandAlliance")
                                        .IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.HasKey("InventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryChunkPlayerDataSnapshotId");
                                });

                            b1.OwnsOne("TacticusPlanner.Persistence.Users.PlayerData.PlayerOrbsRecord", "Orbs", b2 =>
                                {
                                    b2.Property<Guid>("InventoryChunkPlayerDataSnapshotId");

                                    b2.HasKey("InventoryChunkPlayerDataSnapshotId");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("InventoryChunkPlayerDataSnapshotId");

                                    b2.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerRarityAmountRecord", "Chaos", b3 =>
                                        {
                                            b3.Property<Guid>("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<long>("Amount");

                                            b3.Property<string>("Rarity")
                                                .IsRequired();

                                            b3.HasKey("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerRarityAmountRecord", "Imperial", b3 =>
                                        {
                                            b3.Property<Guid>("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<long>("Amount");

                                            b3.Property<string>("Rarity")
                                                .IsRequired();

                                            b3.HasKey("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerRarityAmountRecord", "Xenos", b3 =>
                                        {
                                            b3.Property<Guid>("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<long>("Amount");

                                            b3.Property<string>("Rarity")
                                                .IsRequired();

                                            b3.HasKey("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("PlayerOrbsRecordInventoryChunkPlayerDataSnapshotId");
                                        });

                                    b2.Navigation("Chaos");

                                    b2.Navigation("Imperial");

                                    b2.Navigation("Xenos");
                                });

                            b1.Navigation("AbilityBadges")
                                .IsRequired();

                            b1.Navigation("Components");

                            b1.Navigation("ForgeBadges");

                            b1.Navigation("MythicShards");

                            b1.Navigation("Orbs")
                                .IsRequired();

                            b1.Navigation("Shards");

                            b1.Navigation("XpBooks");
                        });

                    b.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.InventoryItemRecord", "InventoryItems", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<long>("Amount");

                            b1.Property<string>("ItemId")
                                .IsRequired();

                            b1.Property<int>("Level");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("inventory_items")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");
                        });

                    b.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.InventoryUpgradeRecord", "InventoryUpgrades", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<long>("Amount");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("UpgradeId")
                                .IsRequired();

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("inventory_upgrades")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");
                        });

                    b.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.LreProgressRecord", "LreProgress", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("CurrentClaimedChestIndex");

                            b1.Property<int>("CurrentCurrency");

                            b1.Property<int?>("CurrentEventRun");

                            b1.Property<int>("CurrentPoints");

                            b1.Property<int>("CurrentShards");

                            b1.Property<string>("EventId")
                                .IsRequired();

                            b1.Property<int?>("ExtraCurrencyPerPayout");

                            b1.Property<bool?>("HasUsedAdForExtraTokenToday");

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("lre_progress")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");

                            b1.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.LreLaneProgressRecord", "Lanes", b2 =>
                                {
                                    b2.Property<Guid>("LreProgressRecordPlayerDataSnapshotId");

                                    b2.Property<int>("LreProgressRecord__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("LaneId");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.HasKey("LreProgressRecordPlayerDataSnapshotId", "LreProgressRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("LreProgressRecordPlayerDataSnapshotId", "LreProgressRecord__synthesizedOrdinal");

                                    b2.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.LreEncounterProgressRecord", "Encounters", b3 =>
                                        {
                                            b3.Property<Guid>("LreLaneProgressRecordLreProgressRecordPlayerDataSnapshotId");

                                            b3.Property<int>("LreLaneProgressRecordLreProgressRecord__synthesizedOrdinal");

                                            b3.Property<int>("LreLaneProgressRecord__synthesizedOrdinal");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<int>("EncounterPoints");

                                            b3.Property<int>("HighScore");

                                            b3.PrimitiveCollection<string>("ObjectivesCleared")
                                                .IsRequired();

                                            b3.HasKey("LreLaneProgressRecordLreProgressRecordPlayerDataSnapshotId", "LreLaneProgressRecordLreProgressRecord__synthesizedOrdinal", "LreLaneProgressRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                            b3.ToTable("player_data_snapshots");

                                            b3.WithOwner()
                                                .HasForeignKey("LreLaneProgressRecordLreProgressRecordPlayerDataSnapshotId", "LreLaneProgressRecordLreProgressRecord__synthesizedOrdinal", "LreLaneProgressRecord__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Encounters");
                                });

                            b1.OwnsOne("TacticusPlanner.Persistence.Users.PlayerData.TokenBucketRecord", "CurrentEventTokens", b2 =>
                                {
                                    b2.Property<Guid>("LreProgressRecordPlayerDataSnapshotId");

                                    b2.Property<int>("LreProgressRecord__synthesizedOrdinal");

                                    b2.Property<int>("Current");

                                    b2.Property<int>("Max");

                                    b2.Property<int>("NextTokenInSeconds");

                                    b2.Property<int>("RegenDelayInSeconds");

                                    b2.HasKey("LreProgressRecordPlayerDataSnapshotId", "LreProgressRecord__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("LreProgressRecordPlayerDataSnapshotId", "LreProgressRecord__synthesizedOrdinal");
                                });

                            b1.Navigation("CurrentEventTokens");

                            b1.Navigation("Lanes");
                        });

                    b.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.CampaignProgressRecord", "CampaignEventsProgress", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("CatalogCampaignGroupId");

                            b1.Property<int>("HighestObservedBattleIndex");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("TacticusCampaignId")
                                .IsRequired();

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("campaign_events_progress")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");

                            b1.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.CampaignBattleProgressRecord", "Battles", b2 =>
                                {
                                    b2.Property<Guid>("CampaignProgressRecordPlayerDataSnapshotId");

                                    b2.Property<int>("CampaignProgressRecord__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("AttemptsLeft");

                                    b2.Property<int>("AttemptsUsed");

                                    b2.Property<int>("BattleIndex");

                                    b2.HasKey("CampaignProgressRecordPlayerDataSnapshotId", "CampaignProgressRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("CampaignProgressRecordPlayerDataSnapshotId", "CampaignProgressRecord__synthesizedOrdinal");
                                });

                            b1.Navigation("Battles");
                        });

                    b.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.CampaignProgressRecord", "CampaignProgress", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("CatalogCampaignGroupId");

                            b1.Property<int>("HighestObservedBattleIndex");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("TacticusCampaignId")
                                .IsRequired();

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("campaign_progress")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");

                            b1.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.CampaignBattleProgressRecord", "Battles", b2 =>
                                {
                                    b2.Property<Guid>("CampaignProgressRecordPlayerDataSnapshotId");

                                    b2.Property<int>("CampaignProgressRecord__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("AttemptsLeft");

                                    b2.Property<int>("AttemptsUsed");

                                    b2.Property<int>("BattleIndex");

                                    b2.HasKey("CampaignProgressRecordPlayerDataSnapshotId", "CampaignProgressRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("CampaignProgressRecordPlayerDataSnapshotId", "CampaignProgressRecord__synthesizedOrdinal");
                                });

                            b1.Navigation("Battles");
                        });

                    b.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerUnitRecord", "Characters", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.PrimitiveCollection<string>("AppliedUpgradeSlots")
                                .IsRequired();

                            b1.Property<string>("Faction")
                                .IsRequired();

                            b1.Property<string>("GrandAlliance")
                                .IsRequired();

                            b1.Property<long>("MythicShards");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("ProgressionIndex");

                            b1.Property<int>("Rank");

                            b1.Property<long>("Shards");

                            b1.Property<string>("UnitId")
                                .IsRequired();

                            b1.Property<long>("Xp");

                            b1.Property<int>("XpLevel");

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("characters")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");

                            b1.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerUnitAbilityRecord", "Abilities", b2 =>
                                {
                                    b2.Property<Guid>("PlayerUnitRecordPlayerDataSnapshotId");

                                    b2.Property<int>("PlayerUnitRecord__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("AbilityId")
                                        .IsRequired();

                                    b2.Property<int>("Level");

                                    b2.HasKey("PlayerUnitRecordPlayerDataSnapshotId", "PlayerUnitRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerUnitRecordPlayerDataSnapshotId", "PlayerUnitRecord__synthesizedOrdinal");
                                });

                            b1.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerUnitEquipmentSlotRecord", "EquippedItems", b2 =>
                                {
                                    b2.Property<Guid>("PlayerUnitRecordPlayerDataSnapshotId");

                                    b2.Property<int>("PlayerUnitRecord__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("EquipmentId")
                                        .IsRequired();

                                    b2.Property<int>("Level");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Rarity")
                                        .IsRequired();

                                    b2.Property<string>("SlotId")
                                        .IsRequired();

                                    b2.HasKey("PlayerUnitRecordPlayerDataSnapshotId", "PlayerUnitRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerUnitRecordPlayerDataSnapshotId", "PlayerUnitRecord__synthesizedOrdinal");
                                });

                            b1.Navigation("Abilities");

                            b1.Navigation("EquippedItems");
                        });

                    b.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerUnitRecord", "Mows", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.PrimitiveCollection<string>("AppliedUpgradeSlots")
                                .IsRequired();

                            b1.Property<string>("Faction")
                                .IsRequired();

                            b1.Property<string>("GrandAlliance")
                                .IsRequired();

                            b1.Property<long>("MythicShards");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("ProgressionIndex");

                            b1.Property<int>("Rank");

                            b1.Property<long>("Shards");

                            b1.Property<string>("UnitId")
                                .IsRequired();

                            b1.Property<long>("Xp");

                            b1.Property<int>("XpLevel");

                            b1.HasKey("PlayerDataSnapshotId", "__synthesizedOrdinal");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("mows")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");

                            b1.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerUnitAbilityRecord", "Abilities", b2 =>
                                {
                                    b2.Property<Guid>("PlayerUnitRecordPlayerDataSnapshotId");

                                    b2.Property<int>("PlayerUnitRecord__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("AbilityId")
                                        .IsRequired();

                                    b2.Property<int>("Level");

                                    b2.HasKey("PlayerUnitRecordPlayerDataSnapshotId", "PlayerUnitRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerUnitRecordPlayerDataSnapshotId", "PlayerUnitRecord__synthesizedOrdinal");
                                });

                            b1.OwnsMany("TacticusPlanner.Persistence.Users.PlayerData.PlayerUnitEquipmentSlotRecord", "EquippedItems", b2 =>
                                {
                                    b2.Property<Guid>("PlayerUnitRecordPlayerDataSnapshotId");

                                    b2.Property<int>("PlayerUnitRecord__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("EquipmentId")
                                        .IsRequired();

                                    b2.Property<int>("Level");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Rarity")
                                        .IsRequired();

                                    b2.Property<string>("SlotId")
                                        .IsRequired();

                                    b2.HasKey("PlayerUnitRecordPlayerDataSnapshotId", "PlayerUnitRecord__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("player_data_snapshots");

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerUnitRecordPlayerDataSnapshotId", "PlayerUnitRecord__synthesizedOrdinal");
                                });

                            b1.Navigation("Abilities");

                            b1.Navigation("EquippedItems");
                        });

                    b.OwnsOne("TacticusPlanner.Persistence.Users.PlayerData.PlayerDetailsChunk", "PlayerDetails", b1 =>
                        {
                            b1.Property<Guid>("PlayerDataSnapshotId");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("PowerLevel");

                            b1.HasKey("PlayerDataSnapshotId");

                            b1.ToTable("player_data_snapshots");

                            b1
                                .ToJson("player_details")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDataSnapshotId");
                        });

                    b.Navigation("CampaignEventsProgress");

                    b.Navigation("CampaignProgress");

                    b.Navigation("Characters");

                    b.Navigation("GameModeTokens")
                        .IsRequired();

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("InventoryItems");

                    b.Navigation("InventoryUpgrades");

                    b.Navigation("LreProgress");

                    b.Navigation("Mows");

                    b.Navigation("PlayerDetails")
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TacticusPlanner.Persistence.Users.Profile", b =>
                {
                    b.HasOne("TacticusPlanner.Persistence.Users.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("TacticusPlanner.Persistence.Users.Profile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TacticusPlanner.Persistence.Users.TacticusIntegration", b =>
                {
                    b.HasOne("TacticusPlanner.Persistence.Users.Profile", "Profile")
                        .WithOne("TacticusIntegration")
                        .HasForeignKey("TacticusPlanner.Persistence.Users.TacticusIntegration", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TacticusPlanner.Persistence.Users.Account", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TacticusPlanner.Persistence.Users.Profile", b =>
                {
                    b.Navigation("PlayerDataOverride");

                    b.Navigation("PlayerDataSnapshot");

                    b.Navigation("TacticusIntegration");
                });
#pragma warning restore 612, 618
        }
    }
}
